Hide cluster name in tooltip if cells are coloured
ebi-gene-expression-group/scxa-experiment-page-tsne-plot-view pull request #18
Opened 2018-11-01 11:57 UTC by lingyun1010

… by metadata

2018-11-01 12:13 UTC, monicajianu reviewed
While technically correct, I think you could achieve a more elegant solution using the `selectedColourByCategory` prop available to you in the `TsnePlotView` component. Checking contents of strings is never a good idea, especially since that string is set in the backend.

2018-11-20 09:20 UTC, alfonsomunozpomer requested changes
Please, add a test for this case.

2018-11-22 20:01 UTC, alfonsomunozpomer approved these changes
Good! There’s some risk that untested code becomes code rot. Remember to add tests for any new features you add, especially in packages where we already have tests. There are others which are beyond any hope and we will reimplmenet them in time.

Remember to change the function name to keep the linter happy.

2018-11-22 20:01 UTC, alfonsomunozpomer commented on src/ClusterTSnePlot.js
> +const tooltip_header = (clusterType, series, point) => {
Please, use `camelCase` for the function name.

2018-11-23 09:22 UTC, merged