Feature/165972672 restyle download button both
ebi-gene-expression-group/scxa-experiment-page-tsne-plot-view pull request #23
Opened 2019-05-17 13:42 UTC by lingyun1010

2019-05-23 14:33 UTC, monicajianu requested changes
Looks good, but a few unnecessary things could be removed, I think!

2019-05-23 14:33 UTC, monicajianu commented on html/index.html
> +        div.highcharts-button span {
I don't think this actually does anything... Where is the `highcharts-button`? This would only work if we enabled [styled mode](https://www.highcharts.com/docs/chart-design-and-style/style-by-css) for Highcharts, which we don't really want to do. What effect were you trying to achieve?

2019-05-23 14:33 UTC, monicajianu commented on src/plotloader/ScatterPlot.js
> +      fontSize: '15px'
Personally, I think we should keep the font sizes consistent across the page. The menu items should match other labels in the page, I think.

2019-05-23 14:33 UTC, monicajianu commented on src/plotloader/ScatterPlot.js
> +        menuItems: [
I don't think you need to explictly state these menu items, as they are the default values.

2019-05-23 14:33 UTC, monicajianu commented on src/plotloader/highchartsExportStyle.js
> +  H.wrap(H.Renderer.prototype, `label`, function (proceed, str, x, y, shape, anchorX, anchorY, useHTML) {
This looks a little complicated... what is it doing? Also, did you take it from somewhere? If you did, you should attribute the source.

2019-05-23 14:33 UTC, monicajianu commented on src/plotloader/ScatterPlot.js
> +        text: '<i class="icon icon-functional" data-icon="="></i> Download &nbsp;',
I'm guessing the module you wrote deals with this HTML? I can see why you're doing it. Ideally, we would use a simpler mechanism for adding a custom icon (like [here](https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/exporting/buttons-contextbutton-symbol-custom/)), but it looks like the label and the icon are not quite aligned if you increase the font size. Did you look into this approach at all?

2019-05-24 09:02 UTC, lingyun1010 commented on html/index.html
> +        div.highcharts-button span {
This style makes hover effects on export button working well. Otherwise, the button won't be triggered by clicking on the text nor icon.

2019-05-24 09:08 UTC, lingyun1010 commented on src/plotloader/ScatterPlot.js
> +      fontSize: '15px'
I changed to `15px` for both.

2019-05-24 09:08 UTC, lingyun1010 commented on src/plotloader/ScatterPlot.js
> +        menuItems: [
Yes. I have removed `menuItems`.

2019-05-24 09:10 UTC, lingyun1010 commented on src/plotloader/highchartsExportStyle.js
> +  H.wrap(H.Renderer.prototype, `label`, function (proceed, str, x, y, shape, anchorX, anchorY, useHTML) {
It enables highcharts export button to use a component as a title. I have added the source link.

2019-05-24 09:16 UTC, lingyun1010 commented on src/plotloader/ScatterPlot.js
> +        text: '<i class="icon icon-functional" data-icon="="></i> Download &nbsp;',
I did check that, but I would like to keep the icon the same as the heatmap in bulk which is using a component with class `icon icon-functional`. However, the simple mechanism will not allow inserting a normal component here.

2019-06-03 16:24 UTC, alfonsomunozpomer requested changes
More black magic from Torstein Hønsi! Remember to add the `highchartsExportStyle.js` file to the ignored test files. Can you add a test that verifies that, at least, we pass a prop to restyle the button?

2019-06-03 16:24 UTC, alfonsomunozpomer commented on src/plotloader/ScatterPlot.js
> +        text: '<i class="icon icon-functional" data-icon="="></i> Download &nbsp;',
The non-breaking space should be placed between the `<i>` element and the Download word, not the other way around.

2019-06-04 15:37 UTC, alfonsomunozpomer commented on src/plotloader/ScatterPlot.js
> +              color: `black`
These small changes fill my heart with joy. :smile: Glad to see you getting the hang of it!

2019-06-04 15:38 UTC, alfonsomunozpomer approved these changes
Merge away! :+1:

2019-06-04 15:39 UTC, merged